name: Bug report
description: Report a reproducible problem
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps to reproduce.
      placeholder: |
        1. Run command ...
        2. Use URL ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs, stack traces, or screenshots.
      render: shell

  - type: input
    id: version
    attributes:
      label: Project version / commit
      placeholder: e.g. main@abcdef1

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: macOS 14, Go 1.24
